#!/bin/bash

########################################################################
#                              install_ADC
#-----------------------------------------------------------------------
#               A simple script to install the ADC program
########################################################################

#-----------------------------------------------------------------------
# Read target name. If target is not given, then perform a clean install
#-----------------------------------------------------------------------
target=$1

#-----------------------------------------------------------------------
# $args: list of variables to be passed to make
#-----------------------------------------------------------------------
args=""

#-----------------------------------------------------------------------
# Determine the path to the SLEPc install directory
#-----------------------------------------------------------------------
if [ -z $SLEPC_DIR ]; then
    found=false
else
    if [ -d $SLEPC_DIR ]; then
	found=true
    else
	found=false
    fi
fi

if [ "$found" == 'false' ]; then
    if [ -d $HOME/slepc*/conf/ ]; then
	slepcpath=`ls -d $HOME/slepc*/conf/ | sed 's/conf\///g'`
    else
	read -p "Please enter the path to the SLEPc install directory:  " slepcpath	
    fi
else
    slepcpath=$SLEPC_DIR
fi

args+=" "SLEPC_DIR=$slepcpath

#-----------------------------------------------------------------------
# Call to make
#-----------------------------------------------------------------------
if [ -z $target ]; then
    make clean_all $args
    make ww $args
else
    make $target $args
fi
